random_seed: 0 
model_type: DenseModel
hyperparameters:
  loss: mae
  depth: 2
  fit_kwargs:
    batch_size: 512
    epochs: 24
  normalize_loss: true
  width: 128
  regularizer:
    name: l2
    kwargs:
      l: 0.0001
  optimizer:
    name: Adam
    kwargs:
      learning_rate: 0.002
batch_function: batches_from_geodata
batch_kwargs:
  timesteps_per_batch: 10
  mapping_function: open_nudge_to_fine_multiple_datasets
  mapping_kwargs: 
    nudging_variables:
      - "air_temperature"
      - "specific_humidity"
      - "x_wind"
      - "y_wind"
      - "pressure_thickness_of_atmospheric_layer"
    physics_timestep_seconds: 450.0
input_variables:
  - cos_zenith_angle
  - surface_geopotential
  - air_temperature
  - specific_humidity
output_variables:
  - dQ1
  - dQ2
