apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: d474a7bdcedc45a2a310c90664ff313aaf11f2be
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: d474a7bdcedc45a2a310c90664ff313aaf11f2be
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: d474a7bdcedc45a2a310c90664ff313aaf11f2be
  # newTag: 9501a63562e2f16b93605de2e2b00483ec165210

