apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 4c6ec30e80fdbf9f64ecd0e253c21ada146ba976
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 4c6ec30e80fdbf9f64ecd0e253c21ada146ba976
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 4c6ec30e80fdbf9f64ecd0e253c21ada146ba976
