apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 786fe2309c4d48eeefef6a84f932591ee750e9db
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 786fe2309c4d48eeefef6a84f932591ee750e9db
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 786fe2309c4d48eeefef6a84f932591ee750e9db
