model_type: dense
random_seed: 0
cache:
  in_memory: false
  local_download_path: train-data-download-dir
hyperparameters:
  callbacks:
  - kwargs: {}
    name: WandbCallback
  - kwargs:
      monitor: val_loss
      patience: 25
    name: EarlyStopping
  clip_config:
    clip:
      air_temperature:
        start: 25
      specific_humidity:
        start: 25
  dense_network:
    depth: 3
    gaussian_noise: 0.0
    kernel_regularizer:
      kwargs:
        l: 0.0001
      name: l2
    spectral_normalization: false
    width: 419
  input_variables:
  - cos_zenith_angle
  - surface_geopotential
  - air_temperature
  - specific_humidity
  loss:
    loss_type: mae
    scaling: standard
    weight: 1.0
  normalization_fit_samples: 8000
  normalize_loss: true
  optimizer_config:
    kwargs:
      learning_rate: 0.00014
    learning_rate_schedule: null
    name: Adam
  output_variables:
  - dQ1
  - dQ2
  save_model_checkpoints: false
  training_loop:
    batch_size: 512
    epochs: 500
    in_memory: false
    shuffle_buffer_size: 50000
