apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 9e0079998010cc00160d9330fcb6c408f08e359f
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 9e0079998010cc00160d9330fcb6c408f08e359f
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 9e0079998010cc00160d9330fcb6c408f08e359f
