apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: d70d3da1a73df15caee76d74d4b971dbe5351d60
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: d70d3da1a73df15caee76d74d4b971dbe5351d60
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: d70d3da1a73df15caee76d74d4b971dbe5351d60
